import { TMDBDiscover } from '@/common/types/tmdbDiscover'
import { TMDBMovie } from '@/common/types/tmdbMovie';
import { TMDBSerie } from '@/common/types/tmdbSerie';
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import MovieContainer from '@/common/components/movieContainer';
import SerieContainer from '@/common/components/serieContainer';
import Image from 'next/image';

type Props ={
  movies: TMDBMovie[],
  series: TMDBSerie[],
  headerImage: string,
  country: string,
  language: string
}
 export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='flex h-80 md:h-96 lg:h-[25rem] flex-col relative'>
          <div className='w-full h-full bg-cover bg-center'>
            <Image src={`${process.env.THEMOVIEDB_BASE_URL}${process.env.THEMOVIEDB_BACKDROP_SIZE}${props.headerImage}`} fill style={{objectFit: 'cover',}} alt=""/>
            <div className='flex place-content-between backdrop-brightness-50 bg-blue-600/40 flex-col w-full h-full'> 
              <div className='text-white text-2xl sm:text-4xl md:text-5xl lg:text-5xl text-left p-4 mt-3'>
                <span>Bienvenido a MASTERMOVIES! <p className='p-4'/>Aquí encontrarás en qué plataformas puedes ver tus pelis y series favoritas</span>
              </div>              
              <div className='flex items-end text-white h-full p-4 mt-3'>
                <div className="flex flex-grow">
                    <div className="flex flex-1">
                        <input className="rounded-lg text-black grow" type="text"></input>                              
                    </div>                            
                    <div className="flex pl-2">
                        <button className="bg-blue-300 text-blue-950 hover:bg-blue-700 font-bold py-2 px-4 rounded">BUSCAR</button>                                
                    </div> 
                </div> 
              </div>
            </div>
          </div>
        </div>                    
        
        <h2 className='text-2xl pt-4'>Películas populares</h2>
        <MovieContainer country={props.country} language={props.language} movies={props.movies}/>

        <h2 className='text-2xl'>Series populares</h2>
        <SerieContainer series={props.series}/>        
        
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context: GetServerSidePropsContext) => {
  const language: string = context.query?.language?.toString() || "en"

  const randomMovieSerie: number = Math.floor(Math.random() * 2);
  var headerImage: string = ""

  const discoverMovies: TMDBDiscover = await fetch(`${process.env.THEMOVIEDB_API_URL}/discover/movie?api_key=${process.env.THEMOVIEDB_API_KEY}&language=${language}&sort_by=popularity.desc&watch_region=${context.params?.country}&with_watch_monetization_types=flatrate`).then((x) => x.json());
  const discoverSeries: TMDBDiscover = await fetch(`${process.env.THEMOVIEDB_API_URL}/discover/tv?api_key=${process.env.THEMOVIEDB_API_KEY}&language=${language}&sort_by=popularity.desc&watch_region=${context.params?.country}&with_watch_monetization_types=flatrate`).then((x) => x.json());
   
  if(randomMovieSerie == 0){    
    const randomMovie: number = Math.floor(Math.random() * 20);    
    headerImage = `${process.env.THEMOVIEDB_BASE_URL}${process.env.THEMOVIEDB_BACKDROP_SIZE}${discoverMovies.results[randomMovie].backdrop_path}`
  }

  if(randomMovieSerie == 1){
    const randomSerie: number = Math.floor(Math.random() * 20);  
    headerImage = `${process.env.THEMOVIEDB_BASE_URL}${process.env.THEMOVIEDB_BACKDROP_SIZE}${discoverSeries.results[randomSerie].backdrop_path}`
  }   

  context.res.setHeader('Cache-control', `public, s-maxage=432000, max-age=432000, stale-while-revalidate=59`);
  return {
      props: {
        movies: discoverMovies.results,
        series: discoverSeries.results,
        headerImage: headerImage,
        country: context.params?.country,
        language: `${language}-${context.params?.country}`
      }
  }
}
